version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
  adminer:
    container_name: adminer-container
    image: adminer
    restart: always
    ports:
      - 9080:8080
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - 9081:80
      # Change the number before : to the port the SMTP server should be accessible on
      - 9025:25
